AWSTemplateFormatVersion: '2010-09-09'

Description: Java Serverless API Project

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role

    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Effect: Allow

            Principal:
              Service:
                - lambda.amazonaws.com

            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TasksLambda:
    Type: AWS::Lambda::Function

    Properties:
      FunctionName: tasks-java-lambda

      Runtime: java21

      Handler: com.example.Handler::handleRequest

      Role: !GetAtt LambdaExecutionRole.Arn

      MemorySize: 512

      Timeout: 30

      Code:
        S3Bucket: java-serverless-api-braulio
        S3Key: tasks-lambda-1.0.jar

  TasksApi:
    Type: AWS::ApiGateway::RestApi

    Properties:
      Name: TasksApi

  TasksApiResource:
    Type: AWS::ApiGateway::Resource

    Properties:
      RestApiId: !Ref TasksApi

      ParentId: !GetAtt TasksApi.RootResourceId

      PathPart: tasks

  TasksApiMethod:
    Type: AWS::ApiGateway::Method

    Properties:
      RestApiId: !Ref TasksApi

      ResourceId: !Ref TasksApiResource

      HttpMethod: GET

      AuthorizationType: NONE

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TasksLambda.Arn}/invocations'

  LambdaApiPermission:
    Type: AWS::Lambda::Permission

    Properties:
      Action: lambda:InvokeFunction

      FunctionName: !Ref TasksLambda

      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TasksApi}/*/*/*'

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment

    DependsOn:
      - TasksApiMethod

    Properties:
      RestApiId: !Ref TasksApi

      StageName: prod

Outputs:

  ApiUrl:
    Value: !Sub >
      https://${TasksApi}.execute-api.${AWS::Region}.amazonaws.com/prod/tasks